version: '2'

services:
  netdata:
    restart: always
    container_name: netdata
    image: titpetric/netdata:${NETDATA_IMAGEVERSION}
    cap_add:
    - SYS_PTRACE
    ports:
    - "${NETDATA_PORT}:19999"
    volumes:
    - ./data/override:/etc/netdata/override
    - ./data/cache:/var/cache/netdata
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    environment:
    - "NETDATA_PORT=${NETDATA_PORT}"
